# Fly.io app configuration for PlantGuard (Flask + Gunicorn)
# Docs: https://fly.io/docs/reference/configuration/

# You can set a fixed app name here if desired, e.g.:
# app = "plantguard-yourname"
# Otherwise, flyctl launch can generate one interactively.

primary_region = "bom"

[build]
  # A Dockerfile exists at repo root, so Fly will use it automatically.

[env]
  # Optional: configure model location at deploy time using secrets/env
  # MODEL_URL will be used by app.py to download the model if it's not present
  PORT = "5000"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 25

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    method = "get"
    path = "/healthz"
    protocol = "http"
